service: waldo-backend  
useDotenv: true
provider:
  name: aws
  region: ap-south-1 

functions:
  find-waldo:
    handler: dist/lambda.handler 
    events:
      - httpApi: "*"

plugins:
  - serverless-offline 
  - serverless-express 
custom:
  serverless-express:
    find-waldo: ./dist/lambda.js  